# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: effe039ac0e90289f9d86206b563fd6be9b1168d72db622ca5d763ed6a066eb9cfc0587c68501dc01f2948c41d0d67e2e6eaf1d4deebab8bcfe9bb0870820f35

test:
  secret_key_base: 266f9197dd33286292d10c0ba44180e755330de6549d8faee636b468d68d83a4d3fdd73ae3c9f600f99349ccfeba53c1e9acf59caf96855aa13b2265d34586b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
